In [ ]:
import nltk
import numpy as np
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
!pip install gensim
from gensim.models import Word2Vec

nltk.download('punkt')

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 27.4 MB/s eta 0:00:00


In [ ]:
documents = [
    "I love natural language processing",
    "Natural language processing is fun",
    "I love machine learning"
]


In [ ]:
count_vectorizer = CountVectorizer()
bow_counts = count_vectorizer.fit_transform(documents)

print("Vocabulary:")
print(count_vectorizer.get_feature_names_out())

print("\nBag-of-Words (Count Occurrence):")
print(bow_counts.toarray())


Vocabulary:
['fun' 'is' 'language' 'learning' 'love' 'machine' 'natural' 'processing']

Bag-of-Words (Count Occurrence):
[[0 0 1 0 1 0 1 1]
 [1 1 1 0 0 0 1 1]
 [0 0 0 1 1 1 0 0]]


In [ ]:
bow_array = bow_counts.toarray()
normalized_bow = bow_array / bow_array.sum(axis=1, keepdims=True)

print("\nNormalized Bag-of-Words:")
print(normalized_bow)



Normalized Bag-of-Words:
[[0.         0.         0.25       0.         0.25       0.
  0.25       0.25      ]
 [0.2        0.2        0.2        0.         0.         0.
  0.2        0.2       ]
 [0.         0.         0.         0.33333333 0.33333333 0.33333333
  0.         0.        ]]


In [ ]:
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(documents)

print("\nTF-IDF Vocabulary:")
print(tfidf_vectorizer.get_feature_names_out())

print("\nTF-IDF Matrix:")
print(tfidf_matrix.toarray())



TF-IDF Vocabulary:
['fun' 'is' 'language' 'learning' 'love' 'machine' 'natural' 'processing']

TF-IDF Matrix:
[[0.         0.         0.5        0.         0.5        0.
  0.5        0.5       ]
 [0.51741994 0.51741994 0.3935112  0.         0.         0.
  0.3935112  0.3935112 ]
 [0.         0.         0.         0.62276601 0.4736296  0.62276601
  0.         0.        ]]


In [ ]:
documents = [
    "I love natural language processing",
    "Natural language processing is fun",
    "I love machine learning"
]
tokenized_docs = [word_tokenize(doc.lower()) for doc in documents]

NameError: name 'documents' is not defined